### ISSUE TITLE
Error regarding fuse.gvfsd-fuse in output

### ISSUE THREAD

**Issue by iandrewt** [tylerjl/overdue#2]
When the post-transaction hook runs, I get this error at the top every time

```
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
```

I'm using Gnome 3.20.2 on my Arch install

**Comment by tmplt** [comment]
I get the same output, but I'm not using Gnome - if that now is related.

**Comment by tylerjl** [comment]
My guess is we probably just need to null pipe `lsof` stderr via `2>/dev/null` in the pipeline; I'll add the redirect in the script once #1 is merged.

If you'd like to verify this fixes things, you could try changing `lsof -d DEL -F pn0` to `lsof -d DEL -F pn0 2>/dev/null` on-disk before I cut a new release and see if that fixes things.
